README.md

The docs has the wrong URLs for the examples

fix example urls for yml spec

---

pkg/linode-bs/deploy/kubernetes/05-csi-storageclass.yaml

Kubernetes `PersistentVolume`s have an optional parameter that allows
you to define what happens to the volume after its deletion, and after
the deletion of a `PersistentVolumeClaim` that provisioned it. This
inherits from the `StorageClass` used to provision the volume.
The default setting results in the following behavior:
- A `PersistentVolume` is deleted when its `PersistentVolumeClaim` is
deleted
- The underlying block storage volume is deleted when its
`PersistentVolume` is deleted
This is normally what you would expect. However, in some cases this is
not desirable, for instance if the data contained within the volume is
particularly valuable and you don't want to risk inadvertently
deleting it.
By creating a second `StorageClass` using the `Retain` policy, we can
allow users to …

Add additional storage class with 'Retain' ReclaimPolicy

---

README.md
pkg/linode-bs/deploy/releases/linode-blockstorage-csi-driver-v0.1.5.yaml
pkg/linode-bs/examples/kubernetes/csi-pvc.yaml

- Change the default storage class in the deployment manifest to linode-block-storage-retain.
- Change the storage class in the example PVC to
linode-block-storage-retain.
- Update README to reflect these changes.

Change storage class defaults to linode-block-storage-retain

---

pkg/linode-bs/deploy/kubernetes/06-ss-csi-linode-controller.yaml
pkg/linode-bs/deploy/kubernetes/07-ds-csi-linode-node.yaml

These labels are useful when attempting to perform any Kubernetes actions and a filter is needed to only operate on the CSI pods. It's also a convention to label deployments.
1. [X] Does your submission pass tests?
1. [X] Are you addressing a single feature in this PR? 
1. [X] Are your commits atomic, addressing one change per commit?
1. [X] Are you following the conventions of the language? 
1. [X] Have you explained your rationale for why this feature is needed? 

Add labels in CSI daemonset and statefulset

---

.github/workflows/docker-hub.yml
.github/workflows/generate-manifest.yml
.github/workflows/label-sync.yml
.github/workflows/release-drafter.yml

- Alters all workflows to reference actions by their commit SHA rather than their version/tag
- Addresses security concerns described in [GitHub's documentation](https://docs.github.com/en/actions/learn-github-actions/security-hardening-for-github-actions#using-third-party-actions)

Use commit hashes for action references

---

.github/workflows/label-sync.yml

GitHub recently introduced a breaking change that causes workflows referencing Actions by tag SHA to fail. This pull request resolves this issue by changing all Action references to commit SHAs.

Use commit SHA for workflows

---

deploy/kubernetes/base/ds-csi-linode-node.yaml

It is standard practice for provider- and kubernetes-provided critical system daemonsets to come with wildcard tolerations.
Without these, any use of taints on nodes to shape workloads leads to nodes that fail to attach storage.
Even worse, because LKE doesn't support pre-assigning taints to nodepools, you get race conditions because taints have to be applied manually as nodes are added/recycled and come online. So you end up with storage working on a node initially and then randomly failing sometime later after the storage controller crashes and can't restart on any nodes with taints applied, and then it never working on some nodes if you managed to apply taints before the controller got scheduled.

fix(k8s): apply standard tolerations for system daemonsets

---

deploy/kubernetes/base/ss-csi-linode-controller.yaml
e2e/test/csi_driver_test.go
e2e/test/e2e_suite_test.go
e2e/test/framework/namespace.go
e2e/test/framework/pod.go
e2e/test/framework/pvc.go
e2e/test/framework/statefulset.go

This PR adds a new test to the e2e test suite that ensures that a PVC mounted on a rootless container will function as expected.
It also updates the csi-linode-controller manifest to use the most recent CSI images from upstream. This required the addition of a new flag `--default-fstype=ext4` to the `csi-provisioner` container, as it is needed to allow rootless containers to be able to access Volume mounts without changing the permissions of the files.
Finally, it adds critical tolerations to the csi-linode-controller StatefulSet, to allow it to schedule even if a node is `NotReady`.
1. [X] Does your submission pass tests?
1. [X] Have you added tests? 
1. [X] Are your commits atomic, addressing one change per commit?
1. [X] Are you …

Update upstream CSI images & add new e2e test

---

README.md
helm-chart/csi-driver/.helmignore
helm-chart/csi-driver/Chart.yaml
helm-chart/csi-driver/templates/_helpers.tpl
helm-chart/csi-driver/templates/csi-controller-attacher-binding-rbac.yaml
helm-chart/csi-driver/templates/csi-controller-provisioner-binding-rbac.yaml
helm-chart/csi-driver/templates/csi-controller-resizer-binding-rbac.yaml
helm-chart/csi-driver/templates/csi-controller-serviceaccount.yaml
helm-chart/csi-driver/templates/csi-linode-controller.yaml
helm-chart/csi-driver/templates/csi-node-serviceaccount.yaml
helm-chart/csi-driver/templates/csi-secrets.yaml
helm-chart/csi-driver/templates/daemonset.yaml
helm-chart/csi-driver/templates/external-attacher-rbac.yaml
helm-chart/csi-driver/templates/external-provisioner-rbac.yaml
helm-chart/csi-driver/templates/external-resizer-rbac.yaml
helm-chart/csi-driver/templates/get-linode-id.yaml
helm-chart/csi-driver/templates/linode-block-storage-retain.yaml
helm-chart/csi-driver/templates/linode-block-storage.yaml
helm-chart/csi-driver/templates/linode-csi-binding-rbac.yaml
helm-chart/csi-driver/templates/linode-csi-rbac.yaml
helm-chart/csi-driver/templates/linodebs.csi.linode.com.yaml
helm-chart/csi-driver/values.yaml

Adding a helm chart for this component to bring the CSI driver in line with the industry standard of using helm charts to deploy on Kubernetes. This will simplify the deployment process for users. Helm charts are also easier to maintain and understand for developers.
This chart was created using the concatenated yaml file found here: https://raw.githubusercontent.com/linode/linode-blockstorage-csi-driver/master/pkg/linode-bs/deploy/releases/linode-blockstorage-csi-driver.yaml
1. [ ] Have you saved your large formatting changes for a different …

Adding Helm Chart

---

pkg/linode-bs/deploy/releases/linode-blockstorage-csi-driver.yaml

This fixes #61. Nodes created by RKE2 or k3s do not have the spec.ProviderID set to `linode://<linodeID>`. This change verifies that the Node's  spec.Provider ID has the linode:// prefix before writing to to /linode-info/linode-id. If the linode-id file is not populated, the code falls back to looking up the linodeID using its label (which must be the same as its hostname)
2. [ ] Have you added tests? 
3. [x] Are you addressing a single feature in this PR? 
4. [x] Are your commits atomic, addressing one change per commit?
5. [x] Are you following the conventions of the language? 
6. [ ] Have you saved your large formatting changes for a different PR, so we can focus on your work?
7. [x] Have you explained your rationale for why this feature is …

Verify that ProviderID prefix is `linode://` before writing 

---

deploy/kubernetes/base/cm-get-linode-id.yaml
helm-chart/csi-driver/templates/get-linode-id.yaml

Applies the fix from #92 to the helm chart and config map where `get-linode-id` is defined.

fix linode-id in other places

---

deploy/kubernetes/sidecars/external-attacher/rbac.yaml
helm-chart/csi-driver/templates/external-attacher-rbac.yaml

add volumeattachments/status permission to the clusterrole
This fixes #88 

add volumeattachments/status permission to the clusterrole

---

.github/workflows/docker-hub.yml

`git describe` output wasn't being stamped into the binary, but we need it at startup time, so the latest version failed to start.
- I originally wanted to just set `REV: ${{ github.sha }}` and call it a day, but then the stamped version would differ from what we use today (`tag-commits_since-hash`), so I replicated the whole `git describe` call in the action itself to stay consistent.
- I bumped both dependent actions as they were getting a bit old (and used deprecated calls that will be removed from GHA in June)
- Had to increase `fetch-depth` as by default `actions/checkout` only downloads the last commit, but we need the whole history to run our `git describe`
- I considered changing the action to use an official one from Docker, but decided against it to keep the PR minimal. We might …

Embed REV in Docker image

---

helm-chart/csi-driver/templates/linode-block-storage-retain.yaml
helm-chart/csi-driver/templates/linode-block-storage.yaml
helm-chart/csi-driver/values.yaml

There are applicable cases where users may not want to have volumes be retained by default (e.g. testing clusters that have workloads with PVCTemplates that don't define a `storageClassName` in the spec). This change does not change the default storage …

allow the default storage class to be overridden for the helm chart

---

helm-chart/csi-driver/templates/csi-linode-controller.yaml
helm-chart/csi-driver/templates/csi-secrets.yaml
helm-chart/csi-driver/templates/daemonset.yaml
helm-chart/csi-driver/values.yaml

Adding support for passing the LinodeAPIToken and region via secret references instead of raw helm values. This prevents the disclosure of the token in values files when using gitops practices.

Allow passing the linodeApiToken and region via secret references

---

go.mod
pkg/linode-bs/driver.go
pkg/linode-bs/nodeserver.go

closes #62
Implement CSI RPC to support GET_VOLUME_STATS, which allows the kubelet to monitor PVC usage, which is most often used with prometheus and/or kube-prometheus-stack, and can be used to alert when a PVC is close to being full
based off of https://github.com/digitalocean/csi-digitalocean/pull/197
haven't added tests yet, but I built `ghcr.io/beryju/linode-blockstorage-csi-driver:v0.5.2-0-ge8e0af0-dirty` and am testing that in my LKE cluster, which seems to work fine
1. [x] Have you saved your large formatting changes for a different …

initial RPC_GET_VOLUME_STAT support

---

helm-chart/csi-driver/templates/csi-linode-controller.yaml
helm-chart/csi-driver/templates/daemonset.yaml
helm-chart/csi-driver/templates/get-linode-id.yaml
helm-chart/csi-driver/values.yaml

Modify get-linode-id.sh script to
1. Attempt to get the ID from metadata service
2. use dmidecode to fetch the id
3. fallback to fetching it from labels added by the linode-ccm
This fixes #115 

Enhance get-linode-id.sh script to try getting ID from multiple sources

---

pkg/linode-bs/nodeserver.go
pkg/linode-bs/nodeserver_all.go
pkg/linode-bs/nodeserver_windows.go

Getting `NodeGetVolumeStats` implemented added a dependency to `golang.org/x/sys/unix` which will never work on windows nodes. This driver does NOT support Windows nodes but this does make running the unit tests on a windows desktop work and as an open source project we should acknowledge development may happen on any platform.
**Before changes:** 
```
.\nodeserver.go:392:18: undefined: unix.Statfs_t
.\nodeserver.go:394:14: undefined: unix.Statfs
.\nodeserver.go:396:26: undefined: unix.ENOENT
```
**After changes:**  
```
=== RUN   TestDriverSuite
--- PASS: TestDriverSuite (0.00s)
PASS
```

adding windows build tags to hide unix.Statfs calls

---

pkg/linode-bs/controllerserver.go

patching a bug caused by empty tags being passed to the linode api causing a string length error on an empty tag
```
Warning  ProvisioningFailed    15s (x12 over 13m)    linodebs.csi.linode.com_csi-linode-controller-0_9953161e-b804-4677-9f42-94c4bbee3fa7  failed to provision volume with StorageClass  │
│ "linode-block-storage": rpc error: code = Internal desc = [400] [tags] Tag 0 () length must be 3-50 characters 
```

fix empty tags causing length error

---

helm-chart/csi-driver/templates/csi-linode-controller.yaml

This change addresses a small oversight in the Helm chart's csi-linode-controller StatefulSet.

fix: Respect imagePullPolicy for driver in CSI controller StatefulSet

---

pkg/linode-bs/controllerserver.go

This change updates the `LinodeControllerServer.CreateVolume(...)` logic to respect the [idempotency requirements](https://github.com/container-storage-interface/spec/blob/master/spec.md#createvolume) described in the CSI spec. This change should hopefully make volume creation more reliable, especially for long-running and error-prone operations like large volume cloning.
Not currently implemented, see #140.
NOTE: These steps would previously fail because a pre-existing volume would not be respected by CreateVolume(...) after a timeout error.
1. Build the OCI image and push it to an image registry:
```
export REGISTRY_NAME=index.docker.io/mydockerhubuser
export IMAGE_VERSION=dev
```
2. Provision a Kubernetes cluster on Linode. (e.g. RKE2)
3. Navigate to `helm-chart/csi-driver`.
4. Update …

ref: Respect idempotency in CreateVolume(...)

---

e2e/test/csi_driver_test.go
e2e/test/framework/framework.go
e2e/test/framework/pod.go
e2e/test/framework/pvc.go
e2e/test/framework/util.go

Core changes to get these running again and we should pass linting again. To get these running you can boot an LKE cluster and edit the image in the stateful/daemon set for the csi-driver to be an image you build/push to your own image repo. More updates coming to automate that a bit more.
* changed default interval to 1s to make tests run faster, still more to do but this helped cut off 2-3min
* refactored pods/pvcs to have an random int in their name, made them easier to track in kube while watching tests and hopefully we can run them all in parallel some day soon
* found dupe tests running two cleanups
* hardened the funcs around delete/detach to return errors if 404s/notfound/etc
* refactored raw block tests to be a part of the Pod + PVC test
* refactored mkfs.ext4 func to be like the …

Fixing E2E Tests

---

pkg/linode-bs/capabilities.go
pkg/linode-bs/controllerserver.go
pkg/linode-bs/controllerserver_test.go
pkg/linode-bs/driver.go
pkg/linode-bs/driver_test.go
pkg/linode-bs/nodeserver_all.go

Advertises the capability for Controller ListVolumes which resolves #59 . Allows us to run the `external-health-monitor` and get volume health stats for our PVCs. 
The PR also consolidates the places where our driver capabilities are set as I spent far …

Implement ListVolumes

---

helm-chart/csi-driver/templates/daemonset.yaml
helm-chart/csi-driver/values.yaml

Adds a param to configure the pods-mount-dir for the csi plugin daemonset

add ability to configure the pods mount dir to the helm chart

---

pkg/linode-bs/controllerserver.go

Avoid calling detach when Volume is assigned to different LinodeID.

Ensure that LinodeID matches before detach.

---

pkg/linode-bs/nodeserver.go

This is a quick fix for the default case when we have 8 slots and one slot is already taken by boot disk. There may be more slots in use by non-PVC volumes such as swap but they are not the default in LKE.
fixes #154

LKE-3931: Set maxVolumesPerNode to 7

---

pkg/linode-bs/luks.go
pkg/linode-bs/nodeserver.go

Provides a fix for #158 by providing the encryption key on stdin rather than writing it to disk. This eliminates the requirement for `/tmp` to be a tmpfs as we just don't write the key to disk at all. 
I've also made a few other changes to make the …

Write encryptionKey to crypsetup stdin

---

.github/workflows/ci.yml
Makefile
pkg/linode-bs/nodeserver.go
pkg/linode-bs/nodeserver_test.go

**NOTE:** The code change is causing performance regression, as additional checks must be performed when checking if the target is a mount point. This is necessary, as that's how we can reliably detect the bind mounts.

fix: handle bind mounts on same device as expected

---

.github/workflows/ci.yml

The "ci" workflow was previously using the "stable" and "oldstable" versions, which as of Go 1.22 introduces a slight change in how go.mod is formatted. This results in errors like
go: updates to go.mod needed; to update it:
go mod tidy
in the workflow logs.
So instead of relying on mutable version labels like "stable" and "oldstable", this commit binds the version of Go used in CI to be what is specified in the repository's go.mod file.
This will allow us the ability to gradually update Go versions without needing to change the version in more than one place, and keep CI predictable.
1. [x] Are you …

ci: Use go.mod for selecting the Go version

---

pkg/linode-bs/controllerserver.go
pkg/linode-bs/controllerserver_test.go
pkg/linode-bs/limits.go
pkg/linode-bs/limits_test.go
pkg/linode-bs/nodeserver.go
pkg/linode-client/linode-client.go
pkg/metadata/metadata.go

When attaching a block storage volume to a Linode, by default, the Linode API will attempt to persist the attachment across instance reboots by adding the volume ID to the currently-booted instance configuration. This will limit the number of volumes that can be attached to 8, as instance configurations currently only allow attaching local disks and block storage volumes to `sda`..`sdh`.
This change explicitly disables persisting volume attachments across instance boots, when a block storage volume is attached to a running Linode instance. It also adds a pre-attachment check to see if another volume can be attached based on the amount of memory of the host.
The maximum number of volumes that can be attached to a single Linode instance is clamped between 8 and 64, with the allowed number …

pkg/linode-bs: Do not persist volume attachments across boots

---

README.md
deploy/kubernetes/base/ds-csi-linode-node.yaml
deploy/kubernetes/base/ss-csi-linode-controller.yaml
go.mod
go.sum
helm-chart/csi-driver/templates/csi-linode-controller.yaml
helm-chart/csi-driver/templates/daemonset.yaml
helm-chart/csi-driver/values.yaml
main.go

Within the Helm chart templates, the containers running `linode-blockstorage-csi-driver` were being configured with command-line flags where the flags' values were coming from environment variables. This commit removes the middle-man, and drops all of the CSI driver-specific command-line flags in favour of reading configuration values directly from the environment.
The Helm chart and kustomize templates have been updated accordingly.
1. [x] …

Configure the CSI driver through environment variables

---

internal/driver/capabilities.go
internal/driver/driver.go
internal/driver/driver_test.go
internal/driver/utils.go

The driver's capabilities were currently split up across several functions, across several files. This change consolidates all of the capabilities handling into one function per capability type (controller, node, volume access modes).

internal/driver: Simplify set up of driver capabilities

---

helm-chart/csi-driver/templates/get-linode-id.yaml

The get-linode-id script can produce a mangled linode-id when there's a tag with a `id` in there. For example with a metadata response like this
```
backups.enabled: true
backups.status: pending
host_uuid: 2d56ceffafec9f76be86e1d2d1dd37ec2204b28f
id: 60586846
label: jkvbpzyzqaa9pj8ix-master-0
region: us-ord
specs.disk: 163840
specs.gpus: 0
specs.memory: 8192
specs.transfer: 5000
specs.vcpus: 4
tags: cluster:kpp-api-single
tags: clusterUid:jkvbpzyzqaa9pj8ix
tags: prov-from:mgmt-cluster.akamai-kpp.com
type: g6-standard-4
```
the script ends up with
```
60586846clusterUid:jkvbpzyzqaa9pj8i
```
This fixes it by explictly asking for json and looking only at the "id" param.
1. [x] Are you addressing a single feature in this …

Fix script to look at just the id

---

internal/driver/controllerserver.go
internal/driver/controllerserver_test.go
internal/driver/nodeserver.go

When calculating the maximum number of allowed volume attachments, the code was previously taking the ideal maximum number of volumes that could be attached to a node. The way the attachment was calculated, it treated instance disks the same as volumes, which is not correct.
This commit fixes what is effectively an off-by-one error, by subtracting the number of instance disks from the theoretical maximum number of block devices that can be attached to the instance.
In other words, controller and node servers will now report the number of block storage volumes that can be attached, not just block devices.
Fixes #182

internal/driver: Fix off-by-one error with max volume attachments

---

internal/driver/controllerserver.go
internal/driver/driver.go
internal/driver/luks.go
main.go

The driver's name was currently being stored in an unexported const: driverName. This change renames that const symbol to "Name", which results in it being exported from the package.
The driver name was also being redefined in main.go. By exporting the internal/driver.Name const, it lets us use it from main.go.

internal/driver: Rename and export the driver name

---

internal/driver/errors.go
internal/driver/nodeserver.go
internal/driver/nodeserver_helpers.go
internal/driver/nodeserver_helpers_test.go

The cases being addressed here from csi-sanity tests:
- Node Service NodeExpandVolume should fail when no volume id is provided
- Node Service NodeExpandVolume should fail when no volume path is provided
- Node Service NodeExpandVolume should fail when volume is not found
- Node Service NodeExpandVolume should work if node-expand is called after node-publish
**NOTE:** This PR is not for implementing the `NodeExpandVolume()`. That method is in the roadmap for future PRs. This is just meant for address errors related to validation of the request object.
1. [ ] Are you following the conventions of the …

[fix] Address the errors we are seeing for NodeExpandVolume() in CSI-Sanity test

---

Dockerfile
e2e/test/pod-pvc-create-xfs-filesystem/assert-csi-driver-resources.yaml
e2e/test/pod-pvc-create-xfs-filesystem/assert-pvc-pod.yaml
e2e/test/pod-pvc-create-xfs-filesystem/chainsaw-test.yaml
e2e/test/pod-pvc-create-xfs-filesystem/create-pvc-pod.yaml

There was a long standing request to support xfs filesystem within PVCs provisioned by linode-csi-driver: https://www.linode.com/community/questions/20316/create-a-persistentvolume-on-lke-with-a-different-fstype
One of the dependencies were resolved recently which added volumemode=block support: https://github.com/linode/linode-blockstorage-csi-driver/pull/126
However, when provisioning pvcs with fstype as xfs, it was still failing as the mkfs.xfs binary was missing from the pods.
This PR adds this binary so that one can provision PVCs with filesystem of type xfs. Here is the output from csi-linode-plugin container of csi-linode-node pod before and after adding the binary.
Before:
```
/ # ls /sbin/mkfs*
/sbin/mkfs.ext2  /sbin/mkfs.ext3  /sbin/mkfs.ext4  /sbin/mkfs.vfat
```
After:
```
/ # …
```

add xfsprogs to add mkfs.xfs binary to csi-linode-node pod

---

hack/csi-sanity.sh
internal/driver/capabilities.go
internal/driver/controllerserver.go
internal/driver/errors.go

The test cases to address:
- "should fail when requesting to create a volume with already existing name and different capacity"
- We now throwing error with grpc code AlreadyExist when existing vol capacity differs from requested one.
- "should fail when the volume is already published but is incompatible"
- Remove the capability for READONLY volumes since we do not support creating read only volumes on the cloud provider side at the moment. If needed, we could provide readonly capability on the Node Plugin side in future.
1. [ ] Have you …

[Fixes] - Addressing test cases we found running sanity tests for Controller Plugin

---

hack/csi-sanity.sh
internal/driver/capabilities.go

**REASON:** In my previous PR, I removed the functionality for read only volumes because according to the CSI-Driver spec we are suppose to create a read only volume on the Linode side. But Linode currently does not support that. To get around that, we are currently mounting the volume as read-only on the Node plugin side when we publish the volume. To avoid any issues with customer (who might be using it currently), I'm re-enabling it and just skipping the associated csi-sanity test case.
1. [ ] Have you saved your large formatting changes …

[Fix] Re-enable Readonly since we support mounting the volume in that mode on the Node Plugin side

---

internal/driver/nodeserver.go
internal/driver/nodeserver_helpers.go
internal/driver/nodeserver_helpers_test.go

Reason: We introduced errors.go with bunch of predefined errors and funcs() a while back and we want to make sure we use it in the code base to maintain uniformity and consistent error logging

[Cleanup] Replace Status.Error() with helper func() defined in errors.go

---

tests/upstream-e2e/run-tests.sh
tests/upstream-e2e/test-driver.yaml

This PR now tells upstream e2e tests to test ext2, ext3, ext4, xfs as well. This increases our total covered specs from 29 to 45. Here is sample output run:
Before:
```
------------------------------
SSS
------------------------------
[SynchronizedAfterSuite] 
test/e2e/e2e.go:88
Aug 23 15:21:12.453: INFO: Running AfterSuite actions on node 1
[SynchronizedAfterSuite] PASSED [0.000 seconds]
------------------------------
[ReportAfterSuite] Kubernetes e2e suite report
test/e2e/e2e_test.go:161
[ReportAfterSuite] PASSED [0.000 seconds]
------------------------------
Ran 29 of 7692 Specs in 2428.116 seconds
SUCCESS! -- 29 Passed | 0 Failed | 1 Flaked | 0 Pending | 7663 Skipped
PASS
```
After:
```
test/e2e/e2e.go:88
Aug 27 16:22:15.516: INFO: Running AfterSuite actions on node 1 …
```

test ext2, ext3, ext4, xfs as supported filesystem type

---

internal/driver/driver.go
internal/driver/identityserver.go
internal/driver/identityserver_test.go

This PR renames LinodeIdentityServer to IdentityServer and adjusts its fields to align with the naming conventions used in ControllerServer. Additionally, NewIdentityServer() has been moved from driver.go to identityserver.go to improve code organization.
These changes enhance code uniformity and maintainability across the codebase
1. [ ] Have you linked your PR to an …

[Cleanup] Refactor LinodeIdentityServer for uniformity

---

internal/driver/controllerserver.go
tests/upstream-e2e/run-tests.sh

This PR fixes the issue where controller server would not return FS device path if the ControllerPublishVolume() timed out and had to be rerun.
This should fix all the issues we have seen with any test related to MapVolume kubelet error.

[Fix] Controllerserver multivolume fix

---

go.mod
go.sum
internal/driver/metadata.go
main.go
pkg/logger/logger.go

This PR adds the automaxproc library to csi driver
1. [X] Are you addressing a single feature in this PR? 

adding automaxproc to auto optimize GOPROC management

---

internal/driver/errors.go
internal/driver/nodeserver.go
internal/driver/nodeserver_helpers.go
internal/driver/nodeserver_helpers_test.go
tests/csi-sanity/run-tests.sh

Due to previous change with how we now handle getting mount source to close luks volume, it introduced test failures in the csi-sanity tests which went unnoticed. This PR fixes the issue and improved the error propagation from the csi-sanity script.
Example error from CSI-Sanity tests:
`<*errors.errorString | 0xc000404230>{
s: "NodeUnstageVolume for volume ID 6076319-sanitynodefull17047E444ED144616 failed: rpc error: code = Internal desc = Failed to close the luks volume 6076319-sanitynodefull17047E444ED144616: rpc error: code = Internal desc = closeLuksMountSource failed to get mount source 6076319-sanitynodefull17047E444ED144616: invalid input: second part must start with 'pvc'",
},`
1. [ ] Are you addressing a single …

Improve error handling for csi-sanity and fix for failing sanity tests

---

Makefile

When running `devbox run capl-cluster`, the image tag for CSI-driver (if not specified) should be the current branch name. This PR updates that so when we deploy capl-cluster for local testing, by default we will use current branch name as the image tag to deploy CSI driver on capl-cluster
1. [ ] Have you linked your PR to an [open …

[Cleanup] Update the REV var to use current branch name

---

Dockerfile

After dependabot version update for alpine version 3.20.x, we were seeing xfs mounting failures. This is a known issue with alpine version after 3.19. We need to test some solutions before we can bump up the version.
Solution for now is to revert back to 3.18.4 until we find a robust solution for the new version
1. [ ] Have you linked your PR to an [open …

bump alpine version back to 3.18.4

---

.github/workflows/ci.yml
Makefile
internal/driver/controllerserver_helper.go
internal/driver/controllerserver_helper_test.go
internal/driver/luks.go
internal/driver/nodeserver_helpers.go
tests/e2e/test/pod-pvc-basic-filesystem/chainsaw-test.yaml
tests/e2e/test/pod-pvc-create-ext4-filesystem/chainsaw-test.yaml
tests/e2e/test/pod-pvc-create-xfs-filesystem/chainsaw-test.yaml
tests/e2e/test/pod-pvc-expand-raw-block-storage/chainsaw-test.yaml
tests/e2e/test/pod-pvc-expand-storage-size/chainsaw-test.yaml
tests/e2e/test/pod-pvc-luks-mov-volume/chainsaw-test.yaml
tests/e2e/test/pod-pvc-luks/chainsaw-test.yaml
tests/e2e/test/pod-pvc-readonly/chainsaw-test.yaml
tests/e2e/test/statefulset-pvc/chainsaw-test.yaml

[fix] device name when performing luks close

---

deploy/kubernetes/base/ds-csi-linode-node.yaml
deploy/kubernetes/base/ss-csi-linode-controller.yaml
helm-chart/csi-driver/templates/csi-linode-controller.yaml
helm-chart/csi-driver/templates/daemonset.yaml
helm-chart/csi-driver/values.yaml
internal/driver/deploy/releases/linode-blockstorage-csi-driver.yaml
tests/csi-sanity/mkdir_in_pod.sh
tests/csi-sanity/rmdir_in_pod.sh
tests/e2e/test/pod-pvc-luks-mov-volume/chainsaw-test.yaml

In this PR we are removing args for the CSI driver image, the reason for that is we have moved away from setting flags for config and are supporting setting that using env var. 

[Update] Bumping up the version for side cars to latest available versions

---

Makefile

We need to wait for all the nodes to come up before moving on testing. Previously we only waited for control plane nodes to come up but now we are waiting for all nodes. We also set worker nodes to 1 as default.

feat: make the test cluster creation process robust

---

internal/driver/controllerserver.go
internal/driver/controllerserver_helper.go
internal/driver/controllerserver_helper_test.go

volumeContext[VolumeTopologyRegion] was not a reliable source to get volumes region. We saw multiple instances where this was returning an empty string which was causing the region mismatch failure. Switching to just use volume obj returned by API to validate is a better and more robust approach since LinodeVolume Obj returned by the API will always have the correct region field.
1. [ ] Have you explained your rationale for why this feature …

[Bug Fix] AttachVolume error where volume region is empty

---

internal/driver/controllerserver_helper.go

With this PR, we are removing region mismatch check during the volume attachment process. This will not trigger errors in the edge case where the user's volume sometimes does not have region label on the linode backend even though the volume is in the right DC. We will now be relying on the API to return us an error incase there is a region mismatch.
1. [ ] Have you …

[fix] remove region check during volume attachment

---

helm-chart/csi-driver/templates/csi-linode-controller.yaml
helm-chart/csi-driver/templates/daemonset.yaml
helm-chart/csi-driver/values.yaml

This PR allows us to pass environment vars and volumes to CSI driver from helm chart. This will help us to run CSI driver in different environments by just setting the env vars. Following secret and env vars needs to be set to run it in a custom env: …

[improvement] : update helm chart to pass env vars and volumes

---

pkg/linode-client/linode_client.go

This PR removes the custom logic in CSI driver to parse the API URL. We now have UseURL method in linodego which does all the work of setting things correctly based on passed URL. This PR updates CSI driver to use that method instead of SetBaseURL.

[improvement] : remove custom logic from linodeclient, use UseURL method

---

internal/driver/capabilities.go
internal/driver/controllerserver.go
internal/driver/controllerserver_test.go

Report more information in volumeCondition for GET and LIST.

feat: implement GET_VOLUME

---

internal/driver/nodeserver_helpers.go
internal/driver/nodeserver_helpers_linux_test.go
internal/driver/nodeserver_luks_encryption_test.go

We had report on an issue when we try to remount the luks volume. We would get stuck at the validation part (volumeName) when it is expected to not have volume name on reattach. This change ignores that specific check if we are remounting a LUKS volume.
For more info and how to recreate the bug: https://github.com/ErjanGavalji/linode-luks-pv-recreation-error
1. [ ] Have …

[Fix] LUKS device on reattach not executing luksOpen

---

deploy/kubernetes/base/ds-csi-linode-node.yaml
deploy/kubernetes/base/ss-csi-linode-controller.yaml
helm-chart/csi-driver/templates/csi-linode-controller.yaml
helm-chart/csi-driver/templates/daemonset.yaml
internal/driver/deploy/releases/linode-blockstorage-csi-driver.yaml

This explicitly sets the securityContext on the Pods and containers and tries to restrict permissions where possible for privileged containers. Specifically, the csi-linode-plugin container needed to be allowed due to the Bidirectional volume mount propagation requirement but the other containers were set to not allow privileged permissions.
1. [ ] Have you linked your …

set securityContext for Pods and containers

---

tests/e2e/test/pod-pvc-luks-remount/chainsaw-test.yaml

Since adding the new e2e test, I have been noticing that sometime it passes and sometime it doesn't. This is a fix to remove that inconsistency which was caused by VolumeMismatch error due to storageClassname missing when recreating the PVC.

[Bugfix] Fixing LUKS remount e2e test's inconsistency

---

Makefile
tests/csi-sanity/mkdir_in_pod.sh
tests/e2e/test/check-volume-deleted.sh
tests/e2e/test/check-volume-detached.sh
tests/e2e/test/check-volume-size.sh
tests/e2e/test/pod-pvc-basic-filesystem/chainsaw-test.yaml
tests/e2e/test/pod-pvc-create-ext4-filesystem/chainsaw-test.yaml
tests/e2e/test/pod-pvc-create-xfs-filesystem/chainsaw-test.yaml
tests/e2e/test/pod-pvc-expand-raw-block-storage/chainsaw-test.yaml
tests/e2e/test/pod-pvc-expand-storage-size/chainsaw-test.yaml
tests/e2e/test/pod-pvc-linode-encryption/chainsaw-test.yaml
tests/e2e/test/pod-pvc-luks-mov-volume/chainsaw-test.yaml
tests/e2e/test/pod-pvc-luks-remount/chainsaw-test.yaml
tests/e2e/test/pod-pvc-luks/chainsaw-test.yaml
tests/e2e/test/pod-pvc-readonly/chainsaw-test.yaml
tests/e2e/test/statefulset-pvc/chainsaw-test.yaml

- Get linode token and url from linode secret under kube-system
- Count number of nodes using chainsaw function
- Allow to define KUBECONFIG file in Makefile

[test] Allow to use different linode uri

---

tests/e2e/test/pod-pvc-luks-remount/chainsaw-test.yaml

`pod-pvc-luks-remount` test is using /tmp/luks-test when running tests againts multiple environments from one machine it's causing conflicts.

[test] Allow parallel execution of pod-pvc-luks-remount test

---

internal/driver/controllerserver.go

fix(listVolume): only set nextToken if not empty

---

internal/driver/controllerserver_helper.go
internal/driver/controllerserver_helper_test.go

Return linodeID of currently attached linode not the target.

[Bugfix] Return proper linodeID when volume is attached

---

.github/labels.yml

Keeping labels consistent with other linode repos like CAPL

update PR labels

---

internal/driver/controllerserver.go
internal/driver/controllerserver_helper.go
internal/driver/controllerserver_test.go
internal/driver/driver.go
internal/driver/identityserver.go
internal/driver/luks.go
internal/driver/metadata.go
internal/driver/nodeserver.go
internal/driver/nodeserver_all.go
internal/driver/nodeserver_helpers.go
main.go
pkg/logger/logger.go
pkg/logger/logger_test.go

https://github.com/container-storage-interface/spec/blob/master/spec.md#controllerunpublishvolume

Unpublish if no nodeid

---

.github/workflows/ci.yml
internal/driver/controllerserver.go
internal/driver/controllerserver_test.go
internal/driver/nodeserver.go
internal/driver/nodeserver_helpers.go
internal/driver/nodeserver_test.go
tests/e2e/test/pod-pvc-unexpected-reboot/chainsaw-test.yaml
tests/e2e/test/sts-pvc-unexpected-reboot/chainsaw-test.yaml

The main goal of this PR is to reflect current Linode volume behavior.
1) controller resize PV
2) controller ask for node resizing
3) node resizing fail with precondition failing: pv have to be moved
- if volume size in API != real disk size -> need to be moved (detach / attach)
4) when moved, resizing is done and pod can used space
Example:
- editing PVC adding space
- describe pvc
```
Warning  ExternalExpanding         13s (x14 over 4d1h)   volume_expand                             waiting for an external controller to expand this PVC
Normal   Resizing                  13s (x16 over 9m21s)  external-resizer linodebs.csi.linode.com  External resizer is resizing volume pvc-91e59a56f0ce4260
Normal   FileSystemResizeRequired  7s                    external-resizer linodebs.csi.linode.com …
```

Csioffline

---

helm-chart/csi-driver/templates/daemonset.yaml
helm-chart/csi-driver/values.yaml

Related issue: #433 
Currently there is a bunch of hardcoded path in the helm templates which makes it very hard to run k0s or k3s on linode as they have different paths where the data is saved. Without This the csi driver will never register in the cluster and are unable to dynamically assign volumes in linode.
1. [ ] Have you linked your PR to an [open …

feat(volume): and a mounting option for different distros 
