linode/linode-blockstorage-csi-driver

README.md, pkg/linode-bs/deploy/releases/linode-blockstorage-csi-driver-v0.1.3.yaml
`cp pkg/linode-bs/deploy/releases/linode-blockstorage-csi-driver-v0.1.{2,3}.yaml`
`sed -i '' -e "s/0\.1\.2/0\.1\.3/g" ./pkg/linode-bs/deploy/releases/linode-blockstorage-csi-driver-v0.1.3.yaml`
=> Update deployment manifest

pkg/linode-bs/deploy/releases/linode-blockstorage-csi-driver.yaml
Update primary manifest to v0.1.3
=> Update primary manifest to v0.1.3

README.md
=> Fixed broken URL to "Kubernetes CSI" in README.md

pkg/linode-bs/deploy/kubernetes/05-csi-storageclass.yaml
Since the manifest is generated, here is the _real_ update 😄 
- Change storage class default to linode-block-storage-retain
=> Change storage class default to linode-block-storage-retain

README.md
Link to the latest release manifest in the README
=> Link to the latest release manifest in the README

.github/workflows/docker-hub.yml, Makefile
I'll manually push 0.1.7 for now
=> Fix push to docker hub github action

deploy/kubernetes/base/ds-csi-linode-node.yaml
=> Enable priorityClassName in DaemonSet template spec

pkg/linode-bs/controllerserver.go
A race condition can occur during the rescheduling of a workload when a Linode is shutdown. The csi-attacher will attempt to retry the Volume attach if the error returned by ControllerPublishVolume is part of [this set](https://github.com/kubernetes-csi/external-attacher/blob/c4cfca3cd22d7437f0a1d712e3fac30211d6ec09/pkg/attacher/attacher.go#L102).
Using `codes.Unavailable` if the Volume is "still attached" will allow the controller to retry attaching the Volume, rather than return a fatal, final error.
=> Allow Volume attach to retry if Volume is still attached to a Linode

Makefile, app/linode/Dockerfile
=> move go build inside dockerfile from makefile

deploy/kubernetes/base/ds-csi-linode-node.yaml, deploy/kubernetes/base/ss-csi-linode-controller.yaml, pkg/linode-bs/deploy/releases/linode-blockstorage-csi-driver.yaml
=> Updating references from k8s.gcr.io to registry.k8s.io

e2e/test/csi_driver_test.go, e2e/test/framework/pod.go, e2e/test/framework/pvc.go, pkg/linode-bs/controllerserver.go, pkg/linode-bs/examples/kubernetes/csi-app-block.yaml, pkg/linode-bs/examples/kubernetes/csi-pvc-block.yaml, pkg/linode-bs/nodeserver.go
=> VolumeMode=block support

main.go
* forgot to commit the init flags in main
=> forgot InitFlags

.github/workflows/helm.yml, helm-chart/csi-driver/Chart.yaml, helm-chart/csi-driver/values.yaml
This PR adds a workflow for us to test and release our helm chart to a GH page in this repo using [this action](https://github.com/helm/chart-releaser-action)
=> add helm test and publish workflow

.github/workflows/helm.yml, README.md
=> update helm packaging and README for helm installs

deploy/kubernetes/overlays/release/kustomization.yaml.template, devbox.json, devbox.lock, e2e/Makefile, e2e/README.md, hack/generate-yaml.sh
PR includes a handlful of tweaks I needed to make in order to make running e2e tests more viable. PR should be rebased after #163 is merged. 
The odd ordering of TAG and IMAGE_NAME arguments to the hack script are due to not wanting to add actual flags …
=> Capli e2e tweaks

e2e/Makefile, e2e/test/scripts/create_cluster.sh, e2e/test/scripts/create_management_cluster.sh
Small improvements around kubeconfig fetch and renaming management cluster.
=> Polish create cluster script

.github/workflows/release.yml
=> Adding GHCR image build-push support

.github/workflows/helm.yml
=> trigger helm-release off of release tags instead of the main branch

Makefile, hack/release-yaml.sh
=> Fix release process - change paths to manifests

internal/driver/controllerserver.go, internal/driver/controllerserver_test.go, internal/driver/driver.go, internal/driver/errors.go, internal/driver/lifecycle.go
This pull request that cleans up the `LinodeControllerServer` (renamed to `ControllerServer`) in the `internal/driver` package.
This is a brief overview of the changes that have been made in this pull request. Please note that these changes _only_ pertain to the controller server.
- Rename `LinodeControllerServer` to `ControllerServer` &mdash; the "Linode" prefix is somewhat redundant.
- Organize code so that related things are in the same file.
- Document all exported symbols (constants, variables, types, functions and methods).
- Export some constants for documentation purposes &mdash; in some cases, having the constant exported so its documentation is readable can be helpful.
- I have taken most of the "static" errors (ones that do not rely on context-specific information), and moved …
=> internal/driver: Controller cleanup

.github/workflows/ci.yml, README.md
=> add codecov reporting

.github/workflows/ci.yml
=> [Fix] Setting the correct image tag for CSI E2E test image on main branch

Makefile, devbox.json, devbox.lock, e2e/test/pod-pvc-luks/assert-csi-driver-resources.yaml, e2e/test/pod-pvc-luks/assert-pvc-pod.yaml, e2e/test/pod-pvc-luks/chainsaw-test.yaml, e2e/test/pod-pvc-luks/create-pvc-pod.yaml
=> Add LUKS e2e test

.github/workflows/ci.yml, Makefile, devbox.json, e2e/README.md, e2e/test/pod-pvc-basic-filesystem/assert-csi-driver-resources.yaml, e2e/test/pod-pvc-basic-filesystem/chainsaw-test.yaml, e2e/test/pod-pvc-create-ext4-filesystem/assert-csi-driver-resources.yaml, e2e/test/pod-pvc-create-ext4-filesystem/chainsaw-test.yaml, e2e/test/pod-pvc-expand-raw-block-storage/assert-csi-driver-resources.yaml, e2e/test/pod-pvc-expand-raw-block-storage/chainsaw-test.yaml, e2e/test/pod-pvc-expand-storage-size/assert-csi-driver-resources.yaml, e2e/test/pod-pvc-expand-storage-size/chainsaw-test.yaml, e2e/test/pod-pvc-luks/assert-csi-driver-resources.yaml, e2e/test/pod-pvc-luks/chainsaw-test.yaml, e2e/test/statefulset-pvc/assert-csi-driver-resources.yaml, e2e/test/statefulset-pvc/chainsaw-test.yaml, hack/upstream-e2e-tests.sh, tests/upstream-e2e/test-driver.yaml
This PR allows one to run upstream k8s e2e tests for storage class. We intend to run these on the main branch whenever any change is merged to main.
=> [feat] : add support to run upstream k8s e2e tests

.github/workflows/ci.yml
=> [Fix] Update Linode Token to correct one in GHA

e2e/test/pod-pvc-readonly/assert-csi-driver-resources.yaml, e2e/test/pod-pvc-readonly/assert-pvc-pod.yaml, e2e/test/pod-pvc-readonly/chainsaw-test.yaml, e2e/test/pod-pvc-readonly/create-pvc-pod.yaml
=> Adding e2e test to verify ReadOnly volumes are mounted by Node plugin

internal/driver/errors.go, internal/driver/nodeserver.go, internal/driver/nodeserver_helpers.go, internal/driver/nodeserver_helpers_test.go
=> [Clean-Up] Refactor NodeUnpublishVolume()

internal/driver/controllerserver.go, internal/driver/controllerserver_test.go, internal/driver/nodeserver.go, internal/driver/nodeserver_helpers.go, internal/driver/nodeserver_helpers_test.go, pkg/linode-volumes/utils.go, pkg/linode-volumes/utils_test.go
=> [Cleanup] refactor the utils and common pkgs

internal/driver/examples/kubernetes/csi-app.yaml, internal/driver/identityserver.go
=> only support offline expansion; add note on how to use the feature

.github/workflows/ci.yml, .gitignore, Makefile, devbox.json, envrc.example, tests/e2e/README.md
=> add makefile targets and updates

internal/driver/metadata.go, main.go
This PR adds detailed logging to the `GetMetadata` and `GetMetadataFromAPI` functions in the `metadata.go` file.
Key changes:
- Import and use the logger package
- Add log entries for major operations and their outcomes
- Log retrieved metadata details at various verbosity levels. (v=2 for entry/exit of func & v=4 for detailed operations)
1. [ ] Have you linked your PR …
=> [Refactor] Add logging to metadata retrieval functions

.github/workflows/ci.yml, Makefile
=> use commit sha in GHA for docker image version

codecov.yml
=> [feat]: add codecov config and ignore mocks/* code coverage

.github/filters.yml, .github/workflows/ci.yml
=> add gha filter and update ci flow

docs/development-setup.md, docs/testing.md
=> minor documentation updates to development and test experience

internal/driver/controllerserver_test.go
=> [Testing] add tests for controllerserver

internal/driver/nodeserver_test.go
=> add tests for nodeserver methods

internal/driver/identityserver_test.go
=> [Testing] Add more test coverage for identity server

.github/filters.yml, .github/workflows/ci.yml, Makefile, internal/driver/controllerserver.go, internal/driver/controllerserver_test.go
=> fix security issue for int conversion; remove sanity tests if clause

Dockerfile, Makefile, internal/driver/nodeserver_helpers.go
=> bump alpine version to 3.20.3

README.md
=> removing v1.0 disclaimer from readme

devbox.json, devbox.lock, go.mod
=> bump go version to 1.23.2 in go.mod

internal/driver/controllerserver.go, observability/metrics/dashboard.json, pkg/metrics/metrics.go
This PR adds functionality to scrape metrics for functions done by the controller server. 
The functions include:
CreateVolume
DeleteVolume
PublishVolume
UnpublishVolume
=> [feat] controller-server-metrics

Dockerfile
Less rebuild, less network, etc
=> chore: optimize docker layers

Dockerfile
=> chore: shrink useless data in go binary

internal/driver/capabilities.go
Plugin already implements required calls
This enables https://github.com/kubernetes-csi/external-attacher/blob/master/README.md#periodic-re-sync
=> feat: report LIST_VOLUMES_PUBLISHED_NODES cap

Makefile
=> [fix] Fix for failing to initialize the mgmt cluster

.github/release-drafter.yml, .github/workflows/pr-labeler.yml, .github/workflows/release-drafter.yml
=> [ci] Update release drafting process

helm-chart/csi-driver/templates/csi-linode-controller.yaml, helm-chart/csi-driver/values.yaml
=> Add nodeSelector, affinity, and tolerations support to controller StatefulSet

Dockerfile, Dockerfile.dev
=> [Bugfix] passing the vendor version correctly in DockerFile

.github/workflows/ci.yml
=> [feat] enable forked repo PR to run GHA e2e workflow

helm-chart/csi-driver/templates/csi-linode-controller.yaml, helm-chart/csi-driver/templates/daemonset.yaml, helm-chart/csi-driver/values.yaml
=> allow csi driver to have configurable container resources

helm-chart/csi-driver/templates/csi-linode-controller.yaml, helm-chart/csi-driver/templates/daemonset.yaml, helm-chart/csi-driver/values.yaml
=> feat(helm): add podAnnotations and podLabels

.github/workflows/release.yml
See: https://github.com/softprops/action-gh-release/issues/628
=> [deps] pin gh-release action version due to broken latest release
